### ISSUE TITLE
How add file to this image

### ISSUE THREAD

**Issue by texrg** [docker-library/busybox#15]
Hello, I would like to build my program and share it with docker.

Is possible to write simple Makefile how producing simple 'hello world' program and add it to docker (add as layer). What  linking, witch system to compiling etc.

**Comment by yosifkit** [comment]
If you just want to run a C binary in a busybox container, then I think the `hello-world` image is a pretty good example.  We use a separate [dockerfile and image to build the static binary](https://github.com/docker-library/hello-world/blob/f98ccd0399cf3c17a73693448bd6f652c3cf336e/Dockerfile.build) so that the toolchain (compiler) is self contained, and then we copy the binary into the image with another [dockerfile](https://github.com/docker-library/hello-world/blob/f98ccd0399cf3c17a73693448bd6f652c3cf336e/hello-world/Dockerfile).  We do `FROM scratch` for a super tiny container, but it has the drawback of zero debugging since there is no other binary in the image.

The process we use to build, and extract the binaries is contained in [`update.sh`]https://github.com/docker-library/hello-world/blob/f98ccd0399cf3c17a73693448bd6f652c3cf336e/update.sh:
```console
docker build -f Dockerfile.build -t hello-world:build .
rm -rf */hello
docker run --rm hello-world:build sh -c 'tar --create */hello' | tar --extract --wildcards '*/hello'
```
