### ISSUE TITLE
Zip utility in Busybox

### ISSUE THREAD

**Issue by phanirajkiran** [docker-library/busybox#180]
Hi, 
**I want to make a .zip file**, which command can do this zip. I don't see zip command. 

Thanks,
Phanirajkiran

**Comment by yosifkit** [comment]
The `busybox` image just contains the set of utilities provided by the `busybox` binary. If a utility is not in the image, then it probably isn't available via [busybox](https://busybox.net/downloads/BusyBox.html#commands).

`tar` is available to create a compressed tar file with the busybox tools. Alternatively, I'd recommend just using `alpine` and installing any required tools since it is only marginally larger but more generally useful since it has a package manager.
