### ISSUE TITLE
How to Set System Locales in busybox docker image?

### ISSUE THREAD

**Issue by phanirajkiran** [docker-library/busybox#183]
HI, 

I would like to know, how to set system locales in busybox.

Thanks, 
Phani

**Comment by yosifkit** [comment]
You could try the usual environment variables like `LANG` or `LC_ALL`, but I am unsure which, if any, `busybox` implements using. Thier focus is on size and resource optimization (https://busybox.net/about.html).

**Comment by phanirajkiran** [comment]
HI All,
I enabled the Config and made build. But still locale is not active. 
![image](https://github.com/docker-library/busybox/assets/6962311/0c520856-b069-4698-ab68-767074cc2cf8)


docker image i build locally is 
![image](https://github.com/docker-library/busybox/assets/6962311/89016658-74c5-4ba2-93e9-c26bce06ed62)

**Comment by tianon** [comment]
I can't seem to find anything useful about BusyBox's support for locales -- in fact, for me, the second result on Google for "busybox locales" is this very issue. :sob:

If it's supported, I'm not sure whether it's _well_ supported (or perhaps well tested). :see_no_evil:

Most of the use cases for BusyBox are likely explicitly not including locales support because they're typically focused on extremely small form factors that aren't usually used interactively (and thus locale support isn't all that important).
