### ISSUE TITLE
wget: can't execute 'ssl_helper': No such file or directory

### ISSUE THREAD

**Issue by urzds** [docker-library/busybox#25]
It appears that the busybox image is missing the `ssl_helper`:
```
# docker run -ti busybox:1.26.1
(in container) / # wget https://google.com
Connecting to google.com (172.217.16.174:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

**Comment by tianon** [comment]
This is expected -- a basic install of BusyBox doesn't include `ssl_helper` (it's a separate binary, usually linked to something like `matrixssl` or `openssl`), and would complicate our build a bit.

Over in https://github.com/docker-library/busybox/issues/23#issuecomment-270968839, I noted that upstream is starting to release official binaries now, and they also release an `ssl_helper` binary, but there's a strong caveat there that it doesn't do _any_ certificate verification (as far as I could figure out how to enable).

**Comment by devurandom** [comment]
The issue still appears with busybox:1.26.2-musl.

**Comment by tianon** [comment]
@devurandom as I noted above, this is the expected behavior -- without an `ssl_helper`, BusyBox's built-in `wget` cannot download from `https://` sources.

Since BusyBox upstream does not recommend an officially-supported `ssl_helper`, and since it would complicate and increase the size of the build (needing to compile `openssl`, needing to embed and update `ca-certificates`, etc), that is left as an exercise for the reader.

For realistic uses, I think the best solution is probably to use Alpine as a base instead, since it's essentially just BusyBox plus a package manager (suitable for downloading an `ssl_helper` and `ca-certificates`).
