### ISSUE TITLE
Package manager?

### ISSUE THREAD

**Issue by mcandre** [docker-library/busybox#45]
Could library/busybox, specifically library/busybox:uclibc, get a package manager? I'm interested in obtaining a Docker container with uClibC + Go, but I can't seem to find a Docker image with both uClibC and a package manager. Not that there's much chance of a Go package for uClibC, but at least the ability to obtain packages and maybe setup a manual build of Go on uClibC would be nice.

**Comment by tianon** [comment]
Sorry for the delay in responding here.

There's no package manger in this image because BusyBox (upstream, as in https://busybox.net/) does not provide one.  We even build BusyBox itself from source (upstream doesn't reliably provide official pre-compiled binaries, which would also be necessary for a package manager).

Does Go upstream support uClibc?  Last I knew, they had outstanding issues with musl, so I wouldn't be surprised if uClibc is even less well supported ATM.

**Comment by tianon** [comment]
If you're just looking for a build toolchain for uClibc, I'd recommend checking out https://toolchains.bootlin.com/. :+1:

**Comment by tianon** [comment]
(Closing, since we won't add a package manager unless BusyBox upstream does, and they don't seem particularly likely to any time soon. :disappointed:)
