### ISSUE TITLE
create official busybox variant for ARM

### ISSUE THREAD

**Issue by Govinda-Fichtner** [docker-library/busybox#5]
While trying to get Docker integration tests running on ARM one major problem is that the current busybox image only works for x86.

Together with @stefanscherer I created a quick'n'dirty variant of the busybox image which can be found here: https://github.com/hypriot/armhf-busybox

Most of the tests seem to run with it. But we still have a couple of failing tests. This and the facts that the busybox image is crucial for the integration tests makes me think that it would be really important to have a clean port of your busybox image for ARM. And of course it should be part of the official docker-library.

How could we best achieve this? How could I help?

**Comment by hqhq** [comment]
@Govinda-Fichtner Yeah integration test demands some specific configurations for busybox image. I think you should fork https://github.com/docker-library/busybox , and have your own `ubuntu/Dockerfile.builder.armhf` and `upstream/Dockerfile.builder.armhf`.

I worked on this for arm64, but got some problems for `upstream/Dockerfile.builder.aarch64`, anyway @tianon seems toke over and fixed it, now we have https://hub.docker.com/r/aarch64/busybox/ (thanks @tianon , though I don't know how he built it yet, any source files we can see?).

**Comment by hqhq** [comment]
Sorry didn't check your link, you seems already did it based on the official source code. Then I think we should have architecture specific dockerfiles in  https://github.com/docker-library/busybox as we have in Docker, @tianon WDYT?

**Comment by tianon** [comment]
The way I'd done it was somewhat manual, but I've finally got it fixed so that it happens automatically from the existing source here (especially thanks to the refactoring in https://github.com/docker-library/busybox/pull/7); see https://github.com/tianon/jenkins-groovy/blob/master/dsl/docker-multiarch/images/busybox.groovy for the current modifications/build script (and https://github.com/docker-library/gcc/pull/25 for some additional discussion of why I'd rather not commit to completely separate, explicit "multiarch" `Dockerfile`s just yet).

**Comment by tianon** [comment]
I'm going to close this now given the existence of https://hub.docker.com/r/armhf/busybox/, https://hub.docker.com/r/armel/busybox/, and even https://hub.docker.com/r/aarch64/busybox/. :+1:
