### ISSUE TITLE
nslookup doesn't work on 1.31.1

### ISSUE THREAD

**Issue by xinwo** [docker-library/busybox#75]
Reproduce steps
1. kubectl run busybox1 --generator=run-pod/v1 --image=busybox:1.28 -- sleep 3600
2. kubectl run busybox2 --generator=run-pod/v1 --image=busybox:1.31.1 -- sleep 3600
3. kubectl exec -ti busybox1 -- nslookup kubernetes.default
works fine
```
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
```

4. kubectl exec -ti busybox2 -- nslookup kubernetes.default
**not working**
```
Server:         10.96.0.10
Address:        10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

command terminated with exit code 1
```

nslookup works differently on 1.31.1?
what's the correct way to use nslookup on 1.31.1?

**Comment by wglambert** [comment]
This is an upstream BusyBox issue, there was a bug report filed at https://bugs.busybox.net/show_bug.cgi?id=11161

We had a few issues on this
https://github.com/docker-library/busybox/issues/61#issuecomment-528926762, https://github.com/docker-library/busybox/issues/48#issuecomment-418512106

I'm going to close since there isn't anything we can do as maintainers of the image to alleviate this issue and it's been forwarded to upstream
