### ISSUE TITLE
no apk within image, so can't install necessary tools, how to do?

### ISSUE THREAD

**Issue by tscswcn** [docker-library/busybox#89]
no apk within image, so can't install necessary tools, how to do?

**Comment by wglambert** [comment]
https://www.busybox.net/FAQ.html#build_system
BusyBox is a package, it's only a set of programs and not a complete Linux distribution

https://github.com/docker-library/docs/tree/master/busybox#create-a-dockerfile-for-a-binary
>For a simpler alternative that's similarly tiny but easier to extend, see [alpine](https://hub.docker.com/_/alpine/).

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
